#!/usr/bin/env bash

export prefix="\033"
export nc="${prefix}[0m"
export bright="${prefix}[1m"
export dim="${prefix}[2m"
export underscore="${prefix}[4m"
export blink="${prefix}[5m"
export reverse="${prefix}[7m"
export hidden="${prefix}[8m"
export black="${prefix}[30m"
export red="${prefix}[31m"
export green="${prefix}[32m"
export yellow="${prefix}[33m"
export blue="${prefix}[34m"
export magenta="${prefix}[35m"
export cyan="${prefix}[36m"
export white="${prefix}[37m"
export BGblack="${prefix}[40m"
export BGred="${prefix}[41m"
export BGgreen="${prefix}[42m"
export BGyellow="${prefix}[43m"
export BGblue="${prefix}[44m"
export BGmagenta="${prefix}[45m"
export BGcyan="${prefix}[46m"
export BGwhite="${prefix}[47m"
# export TestAwesome="${BGcyan}Cyan text${reset} is ${blink}Awesome!!${reset}"
