# build environment
FROM node:14-slim as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
# RUN npm install react-scripts -g
COPY package.json ./
COPY yarn.lock ./
RUN yarn install --immutable --immutable-cache --check-cache
COPY . ./
ENV GENERATE_SOURCEMAP false
RUN yarn build

# production environment
FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
# new
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]